# server:
#   service:
#     type: LoadBalancer
#   nodeSelector:
#     "node-role.infra": true
# controller:
#   nodeSelector:
#     "node-role.infra": true
# dex:
#   nodeSelector:
#     "node-role.infra": true
# redis:
#   nodeSelector:
#     "node-role.infra": true
# repoServer:
#   nodeSelector:
#     "node-role.infra": true
configs:
  repositories:
    zimagi-repo:
      url: https://zimagi.github.io/charts
      name: zimagi
      type: helm
    elastic-repo:
      url: https://helm.elastic.co
      name: elastic
      type: helm
    metrics-server-repo:
      url: "https://kubernetes-sigs.github.io/metrics-server/"
      name: metrics-server
      type: helm
    prometheus-community-repo:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus-community
      type: helm