name: "Destroy EKS cluster"
on:
  workflow_dispatch:
env:
    AWS_DEFAULT_REGION: us-east-2
jobs:
  terraform_eks_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install terraform cli"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25

      - name: "Terraform format"
        run: terraform fmt -check -no-color
        continue-on-error: false

      - name: "Terraform Init"
        run: terraform init
        continue-on-error: false
        
      # - name: "Terraform Validate"
      #   run: terraform validate -no-color
      #   continue-on-error: false

      - name: "Terraform Destroy"
        run: terraform destroy -no-color -auto-approve
        continue-on-error: false

  destroy_eks_backend:
    name: "Delete aws backend"
    runs-on: ubuntu-latest
    needs: [terraform_eks_destroy]
    steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: "Delete S3 bucket of terraform"
      run: |
        aws s3 rb s3://zimagi-terraform-remote-backend --force