name: "Destroy EKS cluster"
on:
  workflow_dispatch:
env:
  AWS_DEFAULT_REGION: us-east-2
jobs:
  delete_kubernetes_services:
    name: "Delete kubernetes services"
    runs-on: ubuntu-latest
    env:
      REGION: us-east-2
      EKS_CLUSTER_NAME: zimagi
    steps:
    - uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: "Get eks kubeconfig"
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

    - name: "Delete kubernetes services"
      run: |
        NAMESPACES=$(kubectl get namespaces -o=jsonpath='{.items[*].metadata.name}')
        for namespace in $NAMESPACES
        do
          SERVICE_NAMES=$(kubectl get services -n $namespace -o=jsonpath='{.items[*].metadata.name}')
          for service_name in $SERVICE_NAMES
          do
            echo "Delete service $service_name in namespace $namespace"
            kubectl delete service $service_name -n $namespace
          done
        done


  terraform_eks_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    needs: [delete_kubernetes_services]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install terraform cli"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.1

      - name: "Terraform format"
        run: terraform fmt -check -no-color
        continue-on-error: false

      - name: "Terraform Init"
        run: terraform init
        continue-on-error: false
        
      # - name: "Terraform Validate"
      #   run: terraform validate -no-color
      #   continue-on-error: false

      - name: "Terraform Destroy"
        run: terraform destroy -no-color -auto-approve
        continue-on-error: false

  destroy_eks_backend:
    name: "Delete aws backend"
    runs-on: ubuntu-latest
    needs: [terraform_eks_destroy]
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: "Delete S3 bucket of terraform"
        run: |
          aws s3 rb s3://zimagi-terraform-remote-backend --force
