name: "Provision NGINX Ingress Controller"
on:
  workflow_dispatch:
env:
    AWS_DEFAULT_REGION: us-east-2
    EKS_CLUSTER_NAME: zimagi
jobs:
  provision_nginx_ingress_controller:
    name: "Deploy nginx ingress controleer"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: "Get eks kubeconfig"
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

    - name: "Deploy nginx ingress controller"
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add jetstack https://charts.jetstack.io
        helm repo update

        kubectl create namespace nginx-ingress
        helm install nginx-ingress --namespace nginx-ingress bitnami/nginx-ingress-controller -n nginx-ingress

        kubectl create namespace cert-manager
        kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.crds.yaml

        kubectl apply --namespace cert-manager -f ./cluster-issuer.yaml

        helm install cert-manager --namespace cert-manager jetstack/cert-manager --version v0.14.1
