# yamllint disable-line rule:document-start
name: "Provision aws s3 backend"
defaults:
  run:
    shell: bash
    working-directory: modules/terraform-aws-backend
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      aws_default_region:
        description: "Default region of aws"
        required: false
        default: "us-east-2"
      namespace:
        description: "Prefix of the remote backend"
        required: false
        default: "zimagi"
      stage:
        description: "Name of your environment"
        required: false
        default: main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  provision_aws_backend:
    name: "Provision aws backend"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Install aws cli"
        uses: chrislennon/action-aws-cli@v1.1
      - name: "Install terraform cli"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
      # - name: Extract branch name
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: branch_name
      - name: "Terraform format"
        continue-on-error: false
        run: terraform fmt -check -no-color
      - name: "Terraform Init"
        continue-on-error: false
        run: terraform init
      - name: "Terraform Validate"
        continue-on-error: false
        run: terraform validate -no-color
      - name: "Terraform Apply"
        continue-on-error: false
        run: terraform apply -no-color -auto-approve
        env:
          TF_VAR_region: ${{ github.event.inputs.aws_default_region }}
          TF_VAR_namespace: ${{ github.event.inputs.namespace }}
          TF_VAR_stage: ${{ steps.branch_name.outputs.branch }}
      # - name: "Terraform Apply"
      #   continue-on-error: false
      #   run: terraform init -force-copy
      - name: cat
        run: cat backend.tf
