name:  Provision Zimagi Cluster
on:
  workflow_dispatch:
  push:
    paths:
    - 'terraform/zimagi_clusters/*.tfvars'
defaults:
  run:
    working-directory: 'terraform/modules/eks_cluster/examples/complete'
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_CLI_ARGS: '-no-color'
      TFVARS_FILE_PATH: '../../../../zimagi_clusters'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - uses: actions-hub/kubectl@master
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Fmt
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"