name: "Deploy Zimagi to EKS cluster"
on:
  workflow_dispatch:
env:
    AWS_DEFAULT_REGION: us-east-2
    EKS_CLUSTER_NAME: zimagi
jobs:
  deploy_data_api_database:
    name: "Deploy postgresql database"
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: "Get eks kubeconfig"
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

    - name: "Deploy postgresql helm chart"
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        kubectl create namespace data
        helm install data \
        --namespace data \
        --set postgresqlUsername=zimagi \
        --set postgresqlPassword="${{ secrets.POSTGRESQL_PASSWORD }}" \
        --set postgresqlDatabase=zimagi.data \
        --set replication.enabled=true \
        --set replication.slaveReplicas=2 \
        --set replication.synchronousCommit="on" \
        --set replication.numSynchronousReplicas=1 \
        --set metrics.enabled=true \
        --set persistence.enabled=true \
        --set persistence.size=8Gi \
        bitnami/postgresql

  deploy_task_queue:
    name: "Deploy task queue"
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.8'

    - uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: "Get eks kubeconfig"
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

    - name: "Deploy postgresql helm chart"
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        kubectl create namespace tasks
        helm install tasks \
          --namespace tasks \
          --set password="zimagi" \
          --set cluster.slaveCount=3 \
          --set metrics.enabled=true \
          bitnami/redis

  deploy_zimagi:
    name: "Deploy zimagi"
    runs-on: ubuntu-latest
    needs: [deploy_data_api_database, deploy_task_queue]
    steps:
    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.8'

    - uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: "Get eks kubeconfig"
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

    - name: "Add helm repo zimagi"
      run: helm repo add zimagi https://zimagi.github.io/charts

    - name: "Update helm repos"
      run: helm repo update

    - name: "Deploy zimagi"
      run: |
        kubectl create namespace zimagi

        helm install command-api \
          --namespace zimagi \
          --set entrypoint=zimagi-command \
          --set logLevel=warning \
          --set database.host=data-postgresql.data \
          --set database.port=5432 \
          --set database.user=zimagi \
          --set database.pass="zimagi" \
          --set redis.host=tasks-redis-master.tasks \
          --set redis.port=6379 \
          --set redis.pass="zimagi" \
          --set ingress.enabled=true \
          --set "ingress.annotations.nginx\.ingress\.kubernetes\.io\/backend-protocol=HTTPS" \
          --set "ingress.annotations.kubernetes\.io\/ingress\.class=nginx" \
          --set "ingress.annotations.nginx\.ingress\.kubernetes\.io\/rewrite-target=\/$1" \
          --set "ingress.annotations.cert-manager\.io\/cluster-issuer=letsencrypt-prod" \
          --set ingress.hostName="${{ secrets.DOMAIN_NAME }}" \
          --set ingress.http.path="${{ secrets.COMMAND_API_PATH }}" \
          --set ingress.http.servicePort=80 \
          zimagi/zimagi

        helm install data-api \
          --namespace zimagi \
          --set entrypoint=zimagi-data \
          --set logLevel=warning \
          --set database.host=data-postgresql.data \
          --set database.port=5432 \
          --set database.user=zimagi \
          --set database.pass="${{ secrets.POSTGRESQL_PASSWORD }}" \
          --set redis.host=tasks-redis-master.tasks \
          --set redis.port=6379 \
          --set redis.pass="${{ secrets.REDIS_PASSWORD }}" \
          --set ingress.enabled=true \
          --set "ingress.annotations.nginx\.ingress\.kubernetes\.io\/backend-protocol=HTTPS" \
          --set "ingress.annotations.kubernetes\.io\/ingress\.class=nginx" \
          --set "ingress.annotations.nginx\.ingress\.kubernetes\.io\/rewrite-target=\/$1" \
          --set "ingress.annotations.cert-manager\.io\/cluster-issuer=letsencrypt-prod" \
          --set ingress.hostName="${{ secrets.DOMAIN_NAME }}" \
          --set ingress.http.path="${{ secrets.DATA_API_PATH }}" \
          --set ingress.http.servicePort=80 \
          zimagi/zimagi

        helm install scheduler \
          --namespace zimagi \
          --set entrypoint=zimagi-scheduler \
          --set logLevel=warning \
          --set database.host=data-postgresql.data \
          --set database.port=5432 \
          --set database.user=zimagi \
          --set database.pass="${{ secrets.POSTGRESQL_PASSWORD }}" \
          --set redis.host=tasks-redis-master.tasks \
          --set redis.port=6379 \
          --set redis.pass="${{ secrets.REDIS_PASSWORD }}" \
          zimagi/zimagi

        helm install worker \
          --namespace zimagi \
          --set entrypoint=zimagi-worker \
          --set logLevel=warning \
          --set database.host=data-postgresql.data \
          --set database.port=5432 \
          --set database.user=zimagi \
          --set database.pass="${{ secrets.POSTGRESQL_PASSWORD }}" \
          --set redis.host=tasks-redis-master.tasks \
          --set redis.port=6379 \
          --set redis.pass="${{ secrets.REDIS_PASSWORD }}" \
          zimagi/zimagi